# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.CustomContentType')),
            ],
        ),
        migrations.CreateModel(
            name='CustomSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('content_types', models.ManyToManyField(to='administration.CustomContentType')),
                ('filter_fields', models.ManyToManyField(blank=True, related_name='filter_sites', to='administration.CustomField')),
                ('groups', models.ManyToManyField(blank=True, to='auth.Group')),
                ('setting_fields', models.ManyToManyField(blank=True, related_name='setting_sites', to='administration.CustomField')),
                ('sort_fields', models.ManyToManyField(blank=True, related_name='sort_sites', to='administration.CustomField')),
                ('summary_fields', models.ManyToManyField(blank=True, related_name='summary_sites', to='administration.CustomField')),
                ('title_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_sites', to='administration.CustomField')),
            ],
        ),
    ]
